/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE centerBaseService PLEASE EDIT ../center.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Center } from '../../domain/regcovl_db/center';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../center.service.ts
 */

/*
 * SCHEMA DB center
 *
	{
		address: {
			type: 'String'
		},
		name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_student: {
			type: Schema.ObjectId,
			ref : "center"
		},
	}
 *
 */
@Injectable()
export class CenterBaseService {

    contextUrl: string = environment.endpoint + '/center';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * centerService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Center): Observable<Center> {
        return this.http
            .post<Center>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * centerService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * centerService.findBy_student
    *   @description CRUD ACTION findBy_student
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_student(id: string): Observable<Center[]> {
        return this.http
            .get<Center[]>(this.contextUrl + '/findBy_student/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * centerService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Center> {
        return this.http
            .get<Center>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * centerService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Center[]> {
        return this.http
            .get<Center[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * centerService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Center): Observable<Center> {
        return this.http
            .post<Center>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
