/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE departmentBaseService PLEASE EDIT ../department.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Department } from '../../domain/regcovl_db/department';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../department.service.ts
 */

/*
 * SCHEMA DB department
 *
	{
		description: {
			type: 'String'
		},
		name: {
			type: 'String',
			required : true
		},
		program: {
			type: 'String',
			enum : ["BA", "BS"]
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_department: [{
			type: Schema.ObjectId,
			ref : "course"
		}],
		_student: {
			type: Schema.ObjectId,
			ref : "department"
		},
	}
 *
 */
@Injectable()
export class DepartmentBaseService {

    contextUrl: string = environment.endpoint + '/department';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * departmentService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Department): Observable<Department> {
        return this.http
            .post<Department>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * departmentService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * departmentService.findBy_student
    *   @description CRUD ACTION findBy_student
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_student(id: string): Observable<Department[]> {
        return this.http
            .get<Department[]>(this.contextUrl + '/findBy_student/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * departmentService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Department> {
        return this.http
            .get<Department>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * departmentService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Department[]> {
        return this.http
            .get<Department[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * departmentService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Department): Observable<Department> {
        return this.http
            .post<Department>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
