/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE gradeBaseService PLEASE EDIT ../grade.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Grade } from '../../domain/regcovl_db/grade';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../grade.service.ts
 */

/*
 * SCHEMA DB grade
 *
	{
		courseID: {
			type: 'String',
			required : true
		},
		grade: {
			type: 'String',
			required : true
		},
		status: {
			type: 'String',
			enum : ["fail", "noGrade", "pass"]
		},
		studentID: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_courses: {
			type: Schema.ObjectId,
			ref : "grade"
		},
		_student: {
			type: Schema.ObjectId,
			ref : "grade"
		},
	}
 *
 */
@Injectable()
export class GradeBaseService {

    contextUrl: string = environment.endpoint + '/grade';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * gradeService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Grade): Observable<Grade> {
        return this.http
            .post<Grade>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * gradeService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * gradeService.findBy_courses
    *   @description CRUD ACTION findBy_courses
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_courses(id: string): Observable<Grade[]> {
        return this.http
            .get<Grade[]>(this.contextUrl + '/findBy_courses/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * gradeService.findBy_student
    *   @description CRUD ACTION findBy_student
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_student(id: string): Observable<Grade[]> {
        return this.http
            .get<Grade[]>(this.contextUrl + '/findBy_student/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * gradeService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Grade> {
        return this.http
            .get<Grade>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * gradeService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Grade[]> {
        return this.http
            .get<Grade[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * gradeService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Grade): Observable<Grade> {
        return this.http
            .post<Grade>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
